(function(d,k){var i=function(){},q={activeCls:"active-star",hintCls:"hint",errHintCls:"err-hint",activeHintCls:[],starCS:"a",onSelect:i,onCancel:i,onHover:i},p=new Class({Implements:Events,initialize:function(b){this.container=b;this.enterhint=b.getElement(".addenter");this.inputbox=b.getElement(".addfood-box");this.input=b.getElement(".addfood");this.toggleBtn=b.getElement(".for-open");this.createMore();this.bind()},createMore:function(){var b=this.toggleBtn,c=this.container.getElement(".chara-con"),
a=this.container.getElements(".chara-label"),f=!1,h;if(c&&b){c.set("tween",{duration:"short",link:"cancel",onComplete:function(){f&&c.css({overflow:"visible"})}});c.css({overflow:"visible",height:"auto"});h=c.getHeight();32<h?(c.css({height:32,overflow:"hidden"}),b.removeClass("Hide"),b.on("click",function(){f?(c.css({overflow:"hidden"}),h=c.getHeight(),c.tween("height",h,32),b.set("html","展开"),b.set("class","for-open")):(c.tween("height",32,h),b.set("html","收起"),b.set("class","for-close"));f=!f;
return!1})):c.css({height:"auto",overflow:"visible"});for(var e=a.length-1;0<=e;e--)a[e].on("click",function(){if(!b.hasClass("Hide")&&!f){b.set("html","收起");b.set("class","for-close");c.tween("height",32,h)}f=!f})}},positionHint:function(){var b=this.container,c=this.input;this.enterhint.css({left:c.getLeft()-b.getLeft()+c.getWidth()+4,top:c.getTop()-b.getTop()-1})},bind:function(){var b=this,c=this.enterhint,a=this.input,f=this.container.getElement(".chara-con");this.container.on("click",function(a){var e=
$(a.target);e.match(".chara-label")&&(a&&a.preventDefault(),b.toggle(e),b.fireEvent("toggle"))});a.on("focus",function(){c.removeClass("Hide");b.positionHint()});a.on("blur",function(){c.addClass("Hide")});a.on("keyup",function(h){var e=a.get("value").trim();13==h.code&&e&&(a.set("value",""),h=b.container.getElements(".chara-label").filter(function(a){return a.get("html")==e}),h.length?b.toggle(h[0]):(h=b.add(e),b.toggle(h)),b.positionHint(),f.css({overflow:"visible",height:"auto"}))})},val:function(b){if(b)this.container.getElements(".chara-label").forEach(function(c){b.contains(c.get("html"))&&
c.addClass("cur")});else return this.container.getElements(".chara-label").filter(function(b){return b.hasClass("cur")}).map(function(b){return b.get("html")})},toggle:function(b){b.toggleClass("cur")},add:function(b){var c=new Element("a");c.set({"class":"chara-label",href:"javascript:;",text:b});c.inject(this.inputbox,"before");return c},getTitle:function(){return this.container.get("data-title")}}),r=new Class({initialize:function(b,c){var a;if(b=$(b))this.o=a=d.mix(c||{},q,!1),this.wrap=b,this.stars=
b.getElements(a.starCS),(this.hint=a=b.getElement("."+a.hintCls))?this.defaultHint=a.get("text"):this._setHint=i,this._bind()},getRate:function(){return this._rating},getHint:function(){return this.hint.get("text")},setRate:function(b){var c=0,a=this.stars.length,f;if(b||0===b)for(;c<a;c++){if(f=this.stars[c],Number(f.getAttribute("data-rate-value"))===b){this._activeStar(c,b,!0);break}}else this._undo()},check:function(){var b;b=this.getRate();b=!!b||0===b;!b&&this.hint.addClass(this.o.errHintCls);
return b},_undo:function(){this._removeOnCls(this._star);this._star=this._rating=this._index=k;this._setHint()},_bind:function(){var b=this,c=b.o,a,f=clearTimeout,h=setTimeout,e=c.activeCls;b.stars.each(function(d,j){d.hasClass(e)&&(b._activeStar(j),b._setHint(j));d.addEvents({click:function(a){a&&a.preventDefault();b._activeStar(j);c.onSelect.call(b)},mouseenter:function(){f(a);var e=b._star;e&&e!==this&&b._removeOnCls(e);this.addClass(b.o.activeCls);b._setHint(j)},mouseleave:function(){b._removeOnCls(this);
a=h(function(){b._leave()},50)}})});b._bind=i},_activeStar:function(b,c,a){var f=this.stars[b];f&&(this._removeOnCls(this.actived),this._index=b,this._star=f,this._rating=c||Number(f.getAttribute("data-rate-value")),a&&this._leave())},_leave:function(){var b=this._star;b&&b.addClass(this.o.activeCls);this._setHint(this._index)},_removeOnCls:function(b){b&&b.removeClass(this.o.activeCls)},_setHint:function(b){var c=this.o,a=this.stars[b],f=d.isArray(c.activeHintCls)?c.activeHintCls[b]:c.activeHintCls;
this.hint.set("text",a?a.getAttribute("data-hint"):this.defaultHint);this.hint.className=c.hintCls+(f&&b!==k?" "+f:"")}});d.TagList=p;d.StarRating=r})(DP);
(function(){var d=function(){},d=new Class({Implements:[Options],initialize:function(d){var i=this;i.setOptions(d);d=i.options;i.__status=d.status;d.toggleBtn.addEvent(d.eventType,function(d){d.stop();i._changeView()})},options:{eventType:"click",toggles:[{btn:{klass:"on",text:"收起",callback:d},view:{klass:"view-on",callback:d}},{btn:{klass:"off",text:"展开",callback:d},view:{klass:"view-ff",callback:d}}],status:1,toggleBtn:null,viewWrap:null},__status:0,_changeView:function(){var d,i=this.options||
{},q=i.toggleBtn,p=i.viewWrap;d=i.toggles[this.__status];q&&p&&(i=d.btn,d=d.view,q.set("class",i.klass).set("html",i.text),p.set("class",d.klass),i.callback&&i.callback(q,this.__status),d.callback&&d.callback(p,this.__status));this.__status=this.__status?0:1}});DP.Form.ToggleButton=d})(DP);
(function(d){function k(a){return $(q+a)}function i(a,f,b,e,d){for(var c,g,l=0,o=b.length,n,i,k;l<o;l++){n=b[l];if((i=n.getNext("label"))&&(k=i.get("text"))){if(!g&&k===a){g=n;continue}if(!c&&k===f){c=n;continue}}if(c&&g)break}c&&g&&(d&&(a=c,c=g,g=a),a=e?function(){var a=this===false?g.checked||c.checked:this.checked;c.checked=a;g.checked=a}:function(){if(this!==false||c.checked)g.checked=c.checked},c.addEvent("click",a),e&&g.addEvent("click",a),a.call(!1))}var q="J_review-",p=function(){},r=d.Form,
b,c={autoSaveLength:0,leaveConfirm:!1,isShortReview:!1,init:function(){function a(){$$(".review-counter .note").destroy();o.removeEvent("keyup",a);o.onpaste=null}function f(){if(!this.enable||"loaded"!=this.cacheStatus)return!1;var a=this.element.value;this.queryIndex=0;this.queryValue=a;this.update(this.filter(this.cached));return!0}function b(a){var f;a.addEvent("keyup",function(){clearTimeout(f);f=setTimeout(function(){e.saveReviewDraft()},2E3)})}var e=c;d.data("reviewData");var m=d.data("shopID"),
j=[],g=e.expenses=$$(".price-input"),l=e.extinputs=$$(".ext-input");e.extinfo=$$(".ext-info");e.exttaggroup=$$(".charac-list").map(function(a){var f=new d.TagList(a);f.addEvent("toggle",function(){e.saveReviewDraft()});a.type="tagList";a.store("taglist",f);return f});var o=k("body"),n=k("del"),w=k("submit"),x=k("t-btn"),y=$(d.data("reviewWrap")),t,z=[],B=d.StarRating;$$(".J_score_rating").forEach(function(a,f){var b=new B(a,{activeHintCls:"active-hint",activeCls:"active-square",onSelect:e.saveReviewDraft});
b.title=a.get("data-title");z.push(b);var c="rating_"+f;j.push(b);e.__errs[c]=b});e.ratings=z;g.concat(l).forEach(function(a){var e={Double:/^([0-9]+\.?[0-9]{0,2}|)$/,Integer:/^\d{0,8}$/},b=a.get("data-type"),c=a.get("data-options");c&&(c=c.split("|").filter(function(a){return a}),c=new Autocompleter(a,c,{listCloseBtn:!1,fxOptions:!1,width:76,delay:0,adjust:{y:-1},onFocus:f}),c.fetch=f);a.hasClass("calendar")&&new Datepicker(a,a,{triggerType:"focus",preventKey:!0});a.match("input")&&b in e&&new r.InputFilter(a,
e[b],{type:"limit"})});var v=0==d.data("bodyMinCount");r.LengthLimit.prototype.check=function(a){var f=!1,b=this.target.value.length,c=this.target.value==this.target.placeholder?0:this.target.value.replace(this.options.invalidCharsRegExp,"").length;e.isShortReview=!1;if(c<this.options.min){if(v)return this._setInfo(this.options.minMsg,"form-content-block notepart",this.options.min-c),15>c&&(e.isShortReview=!0),!0;this._setInfo(this.options.minMsg,a&&"keyup"==a.type?"form-content-block notepart":"form-content-block overnote",
this.options.min-c)}else b>this.options.max?this._setInfo(this.options.maxMag,"form-content-block overnote",b-this.options.max):(f=!0,this._setInfo(this.options.msg,"form-content-block cannote",this.options.max-b));return f};var s=new r.LengthLimit(o,"J_review-err-body",{invalidCharsRegExp:/[\t\r\n\s]/g,min:v?d.data("bodyAvgCount"):d.data("bodyMinCount"),maxMag:'<span class="note">已超过上限num个字</span>',minMsg:v?'<span class="note">离该商户平均点评字数还差num字':'<span class="note">最少min字，你还需要输入num个字',msg:'<span class="note">你还可以输入num个字',
defClass:"form-content-block notepart"});s._setInfo=function(a,f,b){a=a.replace("min",this.options.min).replace("max",this.options.max).replace("num",b);this.info.className=f;this.info.set("html",a)};var A=function(a){s.check(a)};setTimeout(function(){s.target.removeEvent("keyup").addEvents({keyup:A,blur:A})},0);j.push(s);e.__errs.body=s;new r.PlaceHolder(o);o.addEvent("keyup",a);o.onpaste=a;e.autoSaveLength=o.value.length;n&&n.removeEvents().addEvent("click",function(){confirm("确定要删除此点评？\n\n")&&
(e._disableForm(!0,!0),(new AjaxReq({url:"/ajax/json/review/reviewAction",data:{run:"ad",shopId:m,reviewId:d.data("reviewId")},method:"post",onSuccess:e._submitReturn,onError:e._submitReturn})).send());return!1});0<location.href.indexOf("review")&&(e.leaveConfirm=!0,window.onbeforeunload=function(){if(e.leaveConfirm)return d.data("needAutoSaved")?"您的草稿已保存……":"您的修改尚未提交……"},window.onunload=function(){_hip.push(["mv",{module:"2_reviewfail_leavepage",action:"click",shopid:d.data("shopID")}])});var n=
$("J_review-more-item"),u=$("J_review-options-wrap");if(n&&u){var C=["separated-block open-options","separated-block close-options"],n=function(a,f){a.getParent().set("class",C[f])},u=function(a,f){a[f?"removeClass":"addClass"]("Hide")};new d.Form.ToggleButton({eventType:"click",toggles:[{btn:{klass:"",text:"更多",callback:n},view:{klass:"",callback:u}},{btn:{klass:"off",text:"收起",callback:n},view:{klass:"view-ff",callback:u}}],toggleBtn:$("J_review-more-item"),viewWrap:$("J_review-options-wrap")})}d.data("needAutoSaved")&&
(new AjaxReq({url:"/ajax/json/review/reviewDraftAction",data:{run:"d",mode:"pro",shopId:m},method:"post",onSuccess:e._submitReturn,onError:e._submitReturn})).send();k("ex-features")&&(e.extraTag=new r.PlaceHolder(q+"ex-features"));w&&w.removeEvents().addEvent("click",function(a){a&&a.preventDefault();e._submitCheck()});e.starRating=new d.StarRating("J_shop-rating",{activeHintCls:"active-hint",activeCls:"active-star",onSelect:function(){e.saveReviewDraft()}});e.starRating.title=$("J_shop-rating").get("data-title");
e.checks=j;e.init=p;e._inited=!0;e._bindHash();o.addEvent("focus",function(){e.expand()});x&&x.addEvent("click",function(a){a&&a.preventDefault();e.expand()});if(y&&(t=y.getElements("[type=checkbox]"))&&t.length)i("免费停车","免费停车",t,!0),i("可以刷卡","刷卡消费",t);b(o);l.forEach(b);g.forEach(b);this.initSyncIcons();this.pasteLog()},saveReviewDraft:function(){if(d.data("needAutoSaved")){var a=c,f=a._getReview(),f={run:"s",mode:"pro",shopId:d.data("shopID"),info:JSON.encode(f)};(new AjaxReq({url:"/ajax/json/review/reviewDraftAction",
data:f,method:"post",onSuccess:a._submitReturn,onError:a._submitReturn})).send()}},pasteLog:function(){function a(){_hip.push(["mv",{module:"5_reviewtext_paste",action:"paste",shopid:d.data("shopID")}])}var f=k("body"),b=f.onpaste;f.onpaste=b?function(){a();b()}:a;f.on("click",function(){var a={module:"5_reviewtext_click",action:"click",shopid:d.data("shopID")};window.localStorage&&localStorage.getItem("hippo_rid")&&(a.requestid=localStorage.getItem("hippo_rid"));_hip.push(["mv",a])})},initSyncIcons:function(){var a=
window.page&&page.topDomain||".dianping.com",f=$("J_sync_icons");f&&f.addEvent("click",function(f){var b=f.target,c=b.get("data-type"),d=b.get("href"),g;c&&d&&(f.stop(),g=$("J_sync_"+c),f=g.get("value"),"2"==f?(b.$open=window.open(d),b.$interval=setInterval(function(){var f=Cookie.read("bind_feed");f&&f.toLowerCase()==c&&(Cookie.dispose("bind_feed",{domain:a}),clearInterval(b.$interval),b.$open&&b.$open.close(),delete b.$open,delete b.$interval,b.removeClass(c+"-u").addClass(c+"-o"),g.set("value",
"1"))},100)):"1"==f?(b.removeClass(c+"-o").addClass(c+"-u"),g.set("value","0")):"0"==f&&(b.removeClass(c+"-u").addClass(c+"-o"),g.set("value","1")))})},expand:function(){var a=c;a._inited&&((new Fx.Tween(k("body"),{property:"height",duration:500,transition:Fx.Transitions.Quart.easeOut,onComplete:p})).start(100),a.expand=p)},_bindHash:function(){var a,b;b=DP.delay(function(){var d=location.hash;a!==d&&(a=d,0<d.indexOf("mr")&&(b.cancel(),c.expand()))},100,!0);b.start()},__errs:{},check:function(){var a=
!0;c.checks.each(function(f){var c=f.check();d.data("isShopPage");if(!c&&a&&(f=f.input||f.wrap||f.target)){switch(f.get("id")){case "J_review-s1":b="score1";break;case "J_review-s2":b="score2";break;case "J_review-s3":b="score3";break;case "J_review-body":b="text"}_hip.push(["mv",{module:"8_reviewfail_"+b,action:"click",shopid:d.data("shopID")}])}a=c&&a});return a},_optionalReviewBodyCheck:function(){var a=c;a._getReview();var b=k("body").get("value"),d=0==DP.data("bodyMinCount"),e=d?["添加“签到短评”",
"您的点评字数较少(小于15)，将成为一条签到短评。点击“取消”继续编辑，点击“确定”提交。"]:["重复内容较多","您的点评重复内容较多，建议您修改后提交。点击“取消”返回编辑，点击“确定”继续提交。"];!d&&a._isJunkReviewBody(b)||a.isShortReview?(new Prompt).confirm(e,{onReturn:function(b){b?a._submit():dpga("dp_addreview_cancel_guanshui")}}):a._submit()},_isJunkReviewBody:function(a){for(var b=/[a-zA-Z]{3,}/g,c=/[\u4E00-\u9FFF]/g,e={},m={},j="";null!=(j=b.exec(a));)j in e?e[j]++:e[j]=1;for(;null!=(j=c.exec(a));)j in m?m[j]++:m[j]=1;var b=a=0,g;for(g in e)a++,b+=e[g];e=c=0;for(g in m)c++,e+=
m[g];m=a+c;g=b+e;if(9<a)return!1;e=Math.floor(d.data("bodyMinCount")/2);if(g>=e&&100>g&&0.4<=m/g||100<=g)return!1;dpga("dp_addreview_reminder_guanshui");return!0},_submitCheck:function(){var a=c,f=a.starRating,h=k("body");if(f.check()){var f=a.check(),e=!a.extraCtrl||a.extraCtrl.check();!f||!e?(_hip.push(["mv",{note:h.value.length,type:1,action:"click",shopid:d.data("shopID"),module:"8_review_fail"}]),dpga("dp_addreview_add_invalid_"+b)):a._optionalReviewBodyCheck()}else _hip.push(["mv",{module:"8_reviewfail_shopstar",
action:"click",shopid:d.data("shopID")}]),dpga("dp_addreview_add_invalid_star")},_submit:function(){var a=c,b=a._getReview();a._disableForm(!0);if(a.isShortReview)(new AjaxReq({url:"/ajax/json/review/addShort",data:{content:b.reviewBody,star:b.star.value,shopId:b.shopId},method:"post",onSuccess:a._submitReturn,onError:a._submitReturn})).send();else{var b={run:"a",mode:"pro",info:JSON.encode(b),reviewId:d.data("reviewId"),referPage:document.referrer},h={};["sina","qzone","sohu"].forEach(function(a){var b=
$("J_sync_"+a);b&&(a=b.get("name"),b=b.get("value"),h[a]=b)});d.mix(b,h);for(var e,m=/\+/g,j=/([^&=]+)=?([^&]*)/g,g=window.location.search.substring(1),l={};e=j.exec(g);)l[decodeURIComponent(e[1].replace(m," "))]=decodeURIComponent(e[2].replace(m," "));d.mix(b,l);(new AjaxReq({url:"/ajax/json/review/reviewAction",data:b,method:"post",onSuccess:a._submitReturn,onError:a._submitReturn})).send();_hip.push(["mv",{module:"8_review_success",shopid:d.data("shopID"),action:"click"}])}},_getReview:function(){var a=
c,b=d.data(),h=a.expenses.map(function(a){return{title:a.get("data-title"),value:a.value,desc:a.get("data-desc")}}).filter(function(a){return a.value}),e=a.extinputs.map(function(a){return{title:a.get("data-title"),values:[a.value]}}).concat(a.exttaggroup.map(function(a){return{title:a.getTitle(),values:a.val()}})).filter(function(a){return a.values[0]}),m=b.shopID,j=b.shopType,b=b.cityID,g={title:a.starRating.title,value:a.starRating.getRate(),desc:a.starRating.getHint()},a=a.ratings.map(function(a){return{title:a.title,
value:a.getRate(),desc:a.getHint()}}),l;l=(l=k("body"))&&l.value!==l.get("placeholder")?l.value:"";return{shopId:m,shopType:j,cityId:b,star:g,scoreList:a,reviewBody:l,expenseInfoList:h.length?h:void 0,extInfoList:e.length?e:void 0}},_alertDraft:function(a){var b=c,d=JSON.decode(a);d&&(new Prompt).confirm(["点评草稿箱","你的点评尚未完成，要继续吗？<p class='Color7'>(如果取消，该点评草稿将被删除)</p>"],{onReturn:function(a){a?b._setDraft(d):b._deleteDraft()}})},_deleteDraft:function(){(new AjaxReq({url:"/ajax/json/review/reviewDraftAction",
data:{run:"dd",mode:"pro",shopId:d.data("shopID")},method:"post"})).send()},_setDraft:function(a){var b=c,d=a.reviewBody;if(a){b.autoSaveLength=d.length;a.star&&0<a.star.value&&b.starRating.setRate(a.star.value);a.scoreList&&a.scoreList.forEach(function(a,c){b.ratings[c].setRate(a.value)});if(d){var d=d.cnDecode(),e=k("body");e&&(e.value=d)}a.expenseInfoList&&a.expenseInfoList.forEach(function(a,c){b.expenses[c].set("value",a.value)});a.extInfoList&&b.extinfo.forEach(function(b){var c=b.get("type"),
f=b.get("data-title");"text"==c?a.extInfoList.forEach(function(a){a.title==f&&a.values&&(b.value=a.values[0])}):"tagList"==c&&a.extInfoList.forEach(function(a){a.title==f&&a.values&&b.retrieve("taglist").val(a.values)})});k("body").focus()}},_submitReturn:function(a){var b=c;if(a&&a.code&&a.msg)switch(b._disableForm(!1),a.code){case 200:b._onSuccess(a.msg,a.ugcValidateCode);break;case 201:b._alertDraft(a.msg);break;case 202:case 302:b._autoSaveReturn(a.msg);break;case 300:b._onError(a.msg);break;
case 403:DP.authBox("",b._submit,"addreview_{city}_{channel}".substitute({city:d.data("cityEnName"),channel:d.data("channel")}));break;case 401:case 402:case 404:case 500:b._onHardError(a.msg)}},_autoSaveReturn:function(a){$("J_review-err-asbody").set("html",!a.r?"点评自动保存失败":"点评已经自动保存于 "+a.d)},_disableForm:function(a,b){var c=function(b){for(var c=0,d=arguments,e=d.length,f,h=a;c<e;c++)(f=k(d[c]))&&f.setProperty("disabled",h)},d=k("del"),a=a?"disabled":"";c("s1","s2","s3","ap","body","dtag","stag",
"setag","park","submit","del","ctitle");$$(".J_review-spec-wrap input").each(function(a){c(a)});a?b?d.value="正在删除...":k("submit").value="正在提交...":(d&&(d.value="删除点评"),k("submit").value="提交点评")},_onHardError:function(a){c._disableForm(!1);(new Prompt).alert(a||"发生未知错误，请稍候再试")},_onError:function(a){var b=c,d=b.__errs;b._disableForm(!1);a.s1?d.s1.err(!0):a.s2?d.s2.err(!0):a.s3?d.s3.err(!0):a.ap?d.ap.err(!0):a.body&&d.body.setInfo(a.body,!0)},_onSuccess:function(a,b){var h=c,e="",i=window.location,j=
function(){var a={};i.pathname==e&&(a.r=Math.floor(100*Math.random()));b&&(a.ugcValidateCode=b);a=Object.keys(a).length?"?"+DP.toQueryString(a):"";i.replace(e+a+"")};h.leaveConfirm=!1;if(h.isShortReview)e="/shop/"+d.data("shopID")+"/review_short",dpga("dp_addreview_add_shortreview");else if(a.add){try{var g=document.hippo;g&&g.mv(a.isupdate?"set_rw":"add_rw",a.reviewid)}catch(k){}e="/addreview/success/shop/"+d.data("shopID");dpga("dp_addreview_submitreview_"+d.data("cityEnName")+"_"+d.data("channel"))}else e=
"/member/"+d.data("userID")+"/reviews";a.add&&$("renrenCheck")?$("renrenCheck").checked?(new AjaxReq({url:"/renren.v",data:{"do":"rr"},method:"post",async:!1,onSuccess:function(b){0===b.msg.r&&void 0===a.access&&!0!==a.access?(h._disableForm(!1),a.access=!0,Mbox.open({onClose:function(){h._onSuccess(a)},type:"iframe",url:"/rr_login",size:{x:300,y:140}})):(new AjaxReq({url:"/renren.v",data:{"do":"f",r:a.reviewid,i:a.isupdate?1:0},method:"post",onSuccess:function(a){RenRen.sendXiaoneiFeed(a.msg.id,
a.msg.data,a.msg.content,"",a.msg.title);setTimeout(j,500)}})).send()}})).send():setTimeout(j,100):a.add&&$("sinaCheck")?$("sinaCheck").checked||"checked"==$("sinaCheck").value?(new AjaxReq({url:"/thirdpart.v",data:{"do":"se",tpt:2,ei:a.reviewid,ft:4},method:"post",async:!1,onSuccess:function(){setTimeout(j,100)}})).send():setTimeout(j,100):setTimeout(j,100)}};d.reviewForm=c})(DP);
