(function(i,f){function b(a){this.initSWFUpload(a)}b==f&&(b=function(a){this.initSWFUpload(a)});b.prototype.initSWFUpload=function(a){var d=a.swf_loaded_js_callback,c=a.swf_loaded_err_js_callback;delete a.swf_loaded_js_callback;delete a.swf_loaded_err_js_callback;try{this.customSettings={},this.settings=a,this.eventQueue=[],this.movieName="SWFUpload_"+b.movieCount++,this.movieElement=null,b.instances[this.movieName]=this,this.initSettings(),this.loadFlash(),this.displayDebugInfo(),d&&setTimeout(d,
0)}catch(e){throw delete b.instances[this.movieName],c&&c.delay(0,this),e;}};b.instances={};b.movieCount=0;b.version="2.2.0 2009-03-25";b.QUEUE_ERROR={QUEUE_LIMIT_EXCEEDED:-100,FILE_EXCEEDS_SIZE_LIMIT:-110,ZERO_BYTE_FILE:-120,INVALID_FILETYPE:-130};b.UPLOAD_ERROR={HTTP_ERROR:-200,MISSING_UPLOAD_URL:-210,IO_ERROR:-220,SECURITY_ERROR:-230,UPLOAD_LIMIT_EXCEEDED:-240,UPLOAD_FAILED:-250,SPECIFIED_FILE_ID_NOT_FOUND:-260,FILE_VALIDATION_FAILED:-270,FILE_CANCELLED:-280,UPLOAD_STOPPED:-290};b.FILE_STATUS=
{QUEUED:-1,IN_PROGRESS:-2,ERROR:-3,COMPLETE:-4,CANCELLED:-5};b.BUTTON_ACTION={SELECT_FILE:-100,SELECT_FILES:-110,START_UPLOAD:-120};b.CURSOR={ARROW:-1,HAND:-2};b.WINDOW_MODE={WINDOW:"window",TRANSPARENT:"transparent",OPAQUE:"opaque"};b.completeURL=function(a){if("string"!==typeof a||a.match(/^https?:\/\//i)||a.match(/^\//))return a;var d=window.location.pathname.lastIndexOf("/");path=0>=d?"/":window.location.pathname.substr(0,d)+"/";return path+a};b.prototype.initSettings=function(){this.ensureDefault=
function(a,d){this.settings[a]=this.settings[a]==f?d:this.settings[a]};this.ensureDefault("overload_slice",!1);this.ensureDefault("upload_url","");this.ensureDefault("preserve_relative_urls",!1);this.ensureDefault("file_post_name","Filedata");this.ensureDefault("post_params",{});this.ensureDefault("use_query_string",!1);this.ensureDefault("requeue_on_error",!1);this.ensureDefault("http_success",[]);this.ensureDefault("assume_success_timeout",0);this.ensureDefault("file_types","*.*");this.ensureDefault("file_types_description",
"All Files");this.ensureDefault("file_size_limit",0);this.ensureDefault("file_upload_limit",0);this.ensureDefault("file_queue_limit",0);this.ensureDefault("flash_url","swfupload.swf");Browser.ie?this.ensureDefault("prevent_swf_caching",!0):this.ensureDefault("prevent_swf_caching",!1);this.ensureDefault("button_style",0);this.ensureDefault("button_image_url","");this.ensureDefault("button_width",1);this.ensureDefault("button_height",1);this.ensureDefault("button_text","");this.ensureDefault("button_text_style",
"color: #000000; font-size: 16pt;");this.ensureDefault("button_text_top_padding",0);this.ensureDefault("button_text_left_padding",0);this.ensureDefault("button_action",b.BUTTON_ACTION.SELECT_FILES);this.ensureDefault("button_disabled",!1);this.ensureDefault("button_placeholder_id","");this.ensureDefault("button_placeholder",null);this.ensureDefault("button_cursor",b.CURSOR.HAND);this.ensureDefault("button_window_mode",b.WINDOW_MODE.WINDOW);this.ensureDefault("debug",!1);this.settings.debug_enabled=
this.settings.debug;this.settings.return_upload_start_handler=this.returnUploadStart;this.ensureDefault("swfupload_loaded_handler",null);this.ensureDefault("file_dialog_start_handler",null);this.ensureDefault("file_queued_handler",null);this.ensureDefault("file_queue_error_handler",null);this.ensureDefault("file_dialog_complete_handler",null);this.ensureDefault("upload_start_handler",null);this.ensureDefault("upload_progress_handler",null);this.ensureDefault("upload_error_handler",null);this.ensureDefault("upload_success_handler",
null);this.ensureDefault("upload_complete_handler",null);this.ensureDefault("debug_handler",this.debugMessage);this.ensureDefault("custom_settings",{});this.customSettings=this.settings.custom_settings;this.settings.prevent_swf_caching&&(this.settings.flash_url=this.settings.flash_url+(0>this.settings.flash_url.indexOf("?")?"?":"&")+"preventswfcaching="+(new Date).getTime());this.settings.preserve_relative_urls||(this.settings.upload_url=b.completeURL(this.settings.upload_url),this.settings.button_image_url=
b.completeURL(this.settings.button_image_url));delete this.ensureDefault};b.prototype.loadFlash=function(){var a,d;if(null!==document.getElementById(this.movieName))throw"ID "+this.movieName+" is already in use. The Flash Object could not be added";a=document.getElementById(this.settings.button_placeholder_id)||this.settings.button_placeholder;if(a==f)throw"Could not find the placeholder element: "+this.settings.button_placeholder_id;d=document.createElement("div");d.innerHTML=this.getFlashHTML();
a.parentNode.replaceChild(d.firstChild,a);window[this.movieName]==f&&(window[this.movieName]=this.getMovieElement())};b.prototype.getFlashHTML=function(){return['<object id="',this.movieName,'" type="application/x-shockwave-flash" data="',this.settings.flash_url,'" width="',this.settings.button_width,'" height="',this.settings.button_height,'" class="swfupload"><param name="wmode" value="',this.settings.button_window_mode,'" /><param name="movie" value="',this.settings.flash_url,'" /><param name="quality" value="high" /><param name="menu" value="false" /><param name="allowScriptAccess" value="always" />',
'<param name="flashvars" value="'+this.getFlashVars()+'" />',"</object>"].join("")};b.prototype.getFlashVars=function(){var a=this.buildParamString(),d=this.settings.http_success.join(",");return["movieName=",encodeURIComponent(this.movieName),"&amp;uploadURL=",encodeURIComponent(this.settings.upload_url),"&amp;useQueryString=",encodeURIComponent(this.settings.use_query_string),"&amp;requeueOnError=",encodeURIComponent(this.settings.requeue_on_error),"&amp;httpSuccess=",encodeURIComponent(d),"&amp;assumeSuccessTimeout=",
encodeURIComponent(this.settings.assume_success_timeout),"&amp;params=",encodeURIComponent(a),"&amp;filePostName=",encodeURIComponent(this.settings.file_post_name),"&amp;fileTypes=",encodeURIComponent(this.settings.file_types),"&amp;fileTypesDescription=",encodeURIComponent(this.settings.file_types_description),"&amp;fileSizeLimit=",encodeURIComponent(this.settings.file_size_limit),"&amp;fileUploadLimit=",encodeURIComponent(this.settings.file_upload_limit),"&amp;fileQueueLimit=",encodeURIComponent(this.settings.file_queue_limit),
"&amp;debugEnabled=",encodeURIComponent(this.settings.debug_enabled),"&amp;buttonStyle=",encodeURIComponent(this.settings.debug_enabled),"&amp;buttonImageURL=",encodeURIComponent(this.settings.button_image_url),"&amp;buttonWidth=",encodeURIComponent(this.settings.button_width),"&amp;buttonHeight=",encodeURIComponent(this.settings.button_height),"&amp;buttonText=",encodeURIComponent(this.settings.button_text),"&amp;buttonTextTopPadding=",encodeURIComponent(this.settings.button_text_top_padding),"&amp;buttonTextLeftPadding=",
encodeURIComponent(this.settings.button_text_left_padding),"&amp;buttonTextStyle=",encodeURIComponent(this.settings.button_text_style),"&amp;buttonAction=",encodeURIComponent(this.settings.button_action),"&amp;buttonDisabled=",encodeURIComponent(this.settings.button_disabled),"&amp;buttonCursor=",encodeURIComponent(this.settings.button_cursor),"&amp;overloadSlice=",encodeURIComponent(this.settings.overload_slice)].join("")};b.prototype.getMovieElement=function(){this.movieElement==f&&(this.movieElement=
document.getElementById(this.movieName));if(null===this.movieElement)throw"Could not find Flash element";return this.movieElement};b.prototype.buildParamString=function(){var a=this.settings.post_params,d=[];if("object"===typeof a)for(var b in a)a.hasOwnProperty(b)&&d.push(encodeURIComponent(b.toString())+"="+encodeURIComponent(a[b].toString()));return d.join("&amp;")};b.prototype.destroy=function(){try{this.cancelUpload(null,!1);var a=null;if((a=this.getMovieElement())&&"unknown"===typeof a.CallFunction){for(var d in a)try{"function"===
typeof a[d]&&(a[d]=null)}catch(c){}try{a.parentNode.removeChild(a)}catch(e){}}window[this.movieName]=null;b.instances[this.movieName]=null;delete b.instances[this.movieName];this.movieName=this.eventQueue=this.customSettings=this.settings=this.movieElement=null;this.callFlash("Destroy");return!0}catch(f){return!1}};b.prototype.displayDebugInfo=function(){this.debug(["---SWFUpload Instance Info---\nVersion: ",b.version,"\nMovie Name: ",this.movieName,"\nSettings:\n\tupload_url:               ",this.settings.upload_url,
"\n\tflash_url:                ",this.settings.flash_url,"\n\tuse_query_string:         ",this.settings.use_query_string.toString(),"\n\trequeue_on_error:         ",this.settings.requeue_on_error.toString(),"\n\thttp_success:             ",this.settings.http_success.join(", "),"\n\tassume_success_timeout:   ",this.settings.assume_success_timeout,"\n\tfile_post_name:           ",this.settings.file_post_name,"\n\tpost_params:              ",this.settings.post_params.toString(),"\n\tfile_types:               ",
this.settings.file_types,"\n\tfile_types_description:   ",this.settings.file_types_description,"\n\tfile_size_limit:          ",this.settings.file_size_limit,"\n\tfile_upload_limit:        ",this.settings.file_upload_limit,"\n\tfile_queue_limit:         ",this.settings.file_queue_limit,"\n\tdebug:                    ",this.settings.debug.toString(),"\n\tprevent_swf_caching:      ",this.settings.prevent_swf_caching.toString(),"\n\tbutton_placeholder_id:    ",this.settings.button_placeholder_id.toString(),
"\n\tbutton_placeholder:       ",this.settings.button_placeholder?"Set":"Not Set","\n\tbutton_image_url:         ",this.settings.button_image_url.toString(),"\n\tbutton_width:             ",this.settings.button_width.toString(),"\n\tbutton_height:            ",this.settings.button_height.toString(),"\n\tbutton_text:              ",this.settings.button_text.toString(),"\n\tbutton_text_style:        ",this.settings.button_text_style.toString(),"\n\tbutton_text_top_padding:  ",this.settings.button_text_top_padding.toString(),
"\n\tbutton_text_left_padding: ",this.settings.button_text_left_padding.toString(),"\n\tbutton_action:            ",this.settings.button_action.toString(),"\n\tbutton_disabled:          ",this.settings.button_disabled.toString(),"\n\tcustom_settings:          ",this.settings.custom_settings.toString(),"\nEvent Handlers:\n\tswfupload_loaded_handler assigned:  ",("function"===typeof this.settings.swfupload_loaded_handler).toString(),"\n\tfile_dialog_start_handler assigned: ",("function"===typeof this.settings.file_dialog_start_handler).toString(),
"\n\tfile_queued_handler assigned:       ",("function"===typeof this.settings.file_queued_handler).toString(),"\n\tfile_queue_error_handler assigned:  ",("function"===typeof this.settings.file_queue_error_handler).toString(),"\n\tupload_start_handler assigned:      ",("function"===typeof this.settings.upload_start_handler).toString(),"\n\tupload_progress_handler assigned:   ",("function"===typeof this.settings.upload_progress_handler).toString(),"\n\tupload_error_handler assigned:      ",("function"===
typeof this.settings.upload_error_handler).toString(),"\n\tupload_success_handler assigned:    ",("function"===typeof this.settings.upload_success_handler).toString(),"\n\tupload_complete_handler assigned:   ",("function"===typeof this.settings.upload_complete_handler).toString(),"\n\tdebug_handler assigned:             ",("function"===typeof this.settings.debug_handler).toString(),"\n"].join(""))};b.prototype.addSetting=function(a,d,b){return d==f?this.settings[a]=b:this.settings[a]=d};b.prototype.getSetting=
function(a){return this.settings[a]!=f?this.settings[a]:""};b.prototype.callFlash=function(a,b){var b=b||[],c=this.getMovieElement(),e,g;try{g=c.CallFunction('<invoke name="'+a+'" returntype="javascript">'+__flash__argumentsToXML(b,0)+"</invoke>"),e=eval(g)}catch(h){throw"Call to "+a+" failed";}e!=f&&"object"===typeof e.post&&(e=this.unescapeFilePostParams(e));return e};b.prototype.selectFile=function(){this.callFlash("SelectFile")};b.prototype.selectFiles=function(){this.callFlash("SelectFiles")};
b.prototype.startUpload=function(a){this.callFlash("StartUpload",[a])};b.prototype.cancelUpload=function(a,b){!1!==b&&(b=!0);this.callFlash("CancelUpload",[a,b])};b.prototype.stopUpload=function(){this.debug("stopUpload is called");this.callFlash("StopUpload")};b.prototype.getStats=function(){return this.callFlash("GetStats")};b.prototype.setStats=function(a){this.callFlash("SetStats",[a])};b.prototype.getFile=function(a){return"number"===typeof a?this.callFlash("GetFileByIndex",[a]):this.callFlash("GetFile",
[a])};b.prototype.addFileParam=function(a,b,c){return this.callFlash("AddFileParam",[a,b,c])};b.prototype.removeFileParam=function(a,b){this.callFlash("RemoveFileParam",[a,b])};b.prototype.setUploadURL=function(a){this.settings.upload_url=a.toString();this.callFlash("SetUploadURL",[a])};b.prototype.setPostParams=function(a){this.settings.post_params=a;this.callFlash("SetPostParams",[a])};b.prototype.addPostParam=function(a,b){this.settings.post_params[a]=b;this.callFlash("SetPostParams",[this.settings.post_params])};
b.prototype.removePostParam=function(a){delete this.settings.post_params[a];this.callFlash("SetPostParams",[this.settings.post_params])};b.prototype.setFileTypes=function(a,b){this.settings.file_types=a;this.settings.file_types_description=b;this.callFlash("SetFileTypes",[a,b])};b.prototype.setFileSizeLimit=function(a){this.settings.file_size_limit=a;this.callFlash("SetFileSizeLimit",[a])};b.prototype.setFileUploadLimit=function(a){this.settings.file_upload_limit=a;this.callFlash("SetFileUploadLimit",
[a])};b.prototype.setFileQueueLimit=function(a){this.settings.file_queue_limit=a;this.callFlash("SetFileQueueLimit",[a])};b.prototype.setFilePostName=function(a){this.settings.file_post_name=a;this.callFlash("SetFilePostName",[a])};b.prototype.setUseQueryString=function(a){this.settings.use_query_string=a;this.callFlash("SetUseQueryString",[a])};b.prototype.setRequeueOnError=function(a){this.settings.requeue_on_error=a;this.callFlash("SetRequeueOnError",[a])};b.prototype.setHTTPSuccess=function(a){"string"===
typeof a&&(a=a.replace(" ","").split(","));this.settings.http_success=a;this.callFlash("SetHTTPSuccess",[a])};b.prototype.setAssumeSuccessTimeout=function(a){this.settings.assume_success_timeout=a;this.callFlash("SetAssumeSuccessTimeout",[a])};b.prototype.setDebugEnabled=function(a){this.settings.debug_enabled=a;this.callFlash("SetDebugEnabled",[a])};b.prototype.setButtonStyle=function(a){this.settings.button_style=parseInt(a)||0;this.callFlash("SetButtonStyle",[a])};b.prototype.setButtonImageURL=
function(a){a==f&&(a="");this.settings.button_image_url=a;this.callFlash("SetButtonImageURL",[a])};b.prototype.setButtonDimensions=function(a,b){this.settings.button_width=a;this.settings.button_height=b;var c=this.getMovieElement();c!=f&&(c.style.width=a+"px",c.style.height=b+"px");this.callFlash("SetButtonDimensions",[a,b])};b.prototype.setButtonText=function(a){this.settings.button_text=a;this.callFlash("SetButtonText",[a])};b.prototype.setButtonTextPadding=function(a,b){this.settings.button_text_top_padding=
b;this.settings.button_text_left_padding=a;this.callFlash("SetButtonTextPadding",[a,b])};b.prototype.setButtonTextStyle=function(a){this.settings.button_text_style=a;this.callFlash("SetButtonTextStyle",[a])};b.prototype.setButtonDisabled=function(a){this.settings.button_disabled=a;this.callFlash("SetButtonDisabled",[a])};b.prototype.setButtonAction=function(a){this.settings.button_action=a;this.callFlash("SetButtonAction",[a])};b.prototype.setButtonCursor=function(a){this.settings.button_cursor=a;
this.callFlash("SetButtonCursor",[a])};b.prototype.queueEvent=function(a,b){b==f?b=[]:b instanceof Array||(b=[b]);var c=this;if("function"===typeof this.settings[a])this.eventQueue.push(function(){this.settings[a].apply(this,b)}),setTimeout(function(){c.executeNextEvent()},0);else if(null!==this.settings[a])throw"Event handler "+a+" is unknown or is not a function";};b.prototype.executeNextEvent=function(){var a=this.eventQueue?this.eventQueue.shift():null;"function"===typeof a&&a.apply(this)};b.prototype.unescapeFilePostParams=
function(a){var b=/[$]([0-9a-f]{4})/i,c={},e;if(a!=f){for(var g in a.post)if(a.post.hasOwnProperty(g)){e=g;for(var h;null!==(h=b.exec(e));)e=e.replace(h[0],String.fromCharCode(parseInt("0x"+h[1],16)));c[e]=a.post[g]}a.post=c}return a};b.prototype.testExternalInterface=function(){try{return this.callFlash("TestExternalInterface")}catch(a){return!1}};b.prototype.flashReady=function(){var a=this.getMovieElement();a?(this.cleanUp(a),this.queueEvent("swfupload_loaded_handler")):this.debug("Flash called back ready but the flash movie can't be found.")};
b.prototype.cleanUp=function(a){try{if(this.movieElement&&"unknown"===typeof a.CallFunction){this.debug("Removing Flash functions hooks (this should only run in IE and should prevent memory leaks)");for(var b in a)try{"function"===typeof a[b]&&(a[b]=null)}catch(c){}}}catch(e){}window.__flash__removeCallback=function(a,b){try{a&&(a[b]=null)}catch(d){}}};b.prototype.fileDialogStart=function(){this.queueEvent("file_dialog_start_handler")};b.prototype.fileQueued=function(a){a=this.unescapeFilePostParams(a);
this.queueEvent("file_queued_handler",a)};b.prototype.fileQueueError=function(a,b,c){a=this.unescapeFilePostParams(a);this.queueEvent("file_queue_error_handler",[a,b,c])};b.prototype.fileDialogComplete=function(a,b,c){this.queueEvent("file_dialog_complete_handler",[a,b,c])};b.prototype.uploadStart=function(a){a=this.unescapeFilePostParams(a);this.queueEvent("return_upload_start_handler",a)};b.prototype.returnUploadStart=function(a){var b;if("function"===typeof this.settings.upload_start_handler)a=
this.unescapeFilePostParams(a),b=this.settings.upload_start_handler.call(this,a);else if(this.settings.upload_start_handler!=f)throw"upload_start_handler must be a function";b===f&&(b=!0);this.callFlash("ReturnUploadStart",[!!b])};b.prototype.uploadProgress=function(a,b,c){a=this.unescapeFilePostParams(a);this.queueEvent("upload_progress_handler",[a,b,c])};b.prototype.uploadError=function(a,b,c){a=this.unescapeFilePostParams(a);this.queueEvent("upload_error_handler",[a,b,c])};b.prototype.uploadSuccess=
function(a,b,c){a=this.unescapeFilePostParams(a);this.queueEvent("upload_success_handler",[a,b,c])};b.prototype.uploadComplete=function(a){a=this.unescapeFilePostParams(a);this.queueEvent("upload_complete_handler",a)};b.prototype.debug=function(a){this.queueEvent("debug_handler",a)};b.prototype.debugMessage=function(a){if(this.settings.debug){var d=[];if("object"===typeof a&&"string"===typeof a.name&&"string"===typeof a.message){for(var c in a)a.hasOwnProperty(c)&&d.push(c+": "+a[c]);a=d.join("\n")||
"";d=a.split("\n");a="EXCEPTION: "+d.join("\nEXCEPTION: ")}b.Console.writeLine(a)}};b.Console={};b.Console.writeLine=function(a){var b,c;try{b=document.getElementById("SWFUpload_Console"),b||(c=document.createElement("form"),document.getElementsByTagName("body")[0].appendChild(c),b=document.createElement("textarea"),b.id="SWFUpload_Console",b.style.fontFamily="monospace",b.setAttribute("wrap","off"),b.wrap="off",b.style.overflow="auto",b.style.width="700px",b.style.height="350px",b.style.margin="5px",
c.appendChild(b)),b.value+=a+"\n",b.scrollTop=b.scrollHeight-b.clientHeight}catch(e){alert("Exception: "+e.name+" Message: "+e.message)}};window.SWFUpload=b;i.SWFUpload=b})(DP);DP.define(function(){return SWFUpload});
