DP.Form.InputFilter=new Class({Implements:Options,options:{periodical:100,delay:10,modifiers:"i",type:"filter",onlyFocus:!0,onStart:$empty},initialize:function(a,b,c){var d=this;if((a=$(a))&&b){this.setOptions(c);switch($type(b)){case "string":b=new RexExp(b,d.options.modifiers);case "regexp":var e=b,b="filter"===d.options.type?function(a){return!e.test(a)}:function(a){return e.test(a)};break;case "function":b=b.bind(this);break;default:return}d.input=a;d.filter=b;d.value="";d.check=d.check.bind(d);
d.options.onlyFocus?a.addEvents({focus:function(){d.checkOn=!0},blur:function(){d.checkOn=!1}}):d.checkOn=!0;d.options.onStart!==$empty&&d.options.onStart.call(d,a);d.observer=new Observer(a,d.check,{periodical:d.options.periodical,delay:d.options.delay})}},check:function(a){this.checkOn&&this.value!==a&&(this.filter(a)?this.value=a:this.input.set("value",this.value))}});
(function(a){function b(a,b){var c=b[a];b[a]=function(){return c.apply(b,arguments)}}function c(b){return"array"===a.type(b)?b:[b]}var d=a.Form,e=new Class({Implements:Options,options:{errClass:"err-input",ev:"blur",showErr:!0},initialize:function(a,f,d,j,h){var a=$(a),f=$(f),e=this;if(a&&d){e.setOptions(h);h=e.options;e.input=a;e.errHolder=f;e.criteria=c(d);e.msg=c(j||[]);c(h.showErr);f=c(h.ev);h=function(){e.check()};a.match("select")&&(f.contains("change")||f.push("change"),f.erase("blur"));d=
0;for(j=f.length;d<j;d++)"observer"===f[d]?new Observer(a,h,{delay:100}):a.addEvent(f[d],h)}b("getValue",e);b("check",e);b("err",e)},check:function(a){for(var b=!0,d=0,c=this,e=c.criteria,n=e.length,k,m=c.getValue(),l;d<n;++d)if(k=e[d],l=c.msg[d],k.ajax)k(m,function(b){return function(d,e){c.err(!d,a?null:e||b)}}(l));else if(!k(m)){c.err(!0,l);b=!1;break}b&&c.err(!1);return b},err:function(a,b){var d=this.errHolder,c=this.options.errClass;a?(d&&(d.removeClass("Hide"),(b||""===b)&&d.set("text",b)),
this.input.addClass(c)):(d&&d.addClass("Hide"),this.input.removeClass(c))},getValue:function(){return this.input.get("value").trim()}});d.InputChecker=e})(DP);
DP.Form.LengthLimit=new Class({Implements:[Options,Events],options:{errorClass:"fv-err",defClass:"fv-def",min:50,max:2E3,minMsg:"你还需要输入<em>num</em>个字",maxMag:"你最多只能输入<em>max</em>个字，多写<em>num</em>个",msg:"你还可以输入<em>num</em>个字",invalidCharsRegExp:/[\.。，,；：;:@~～!！#￥$＠\-=·+*?？＠_*%#、\r\n\s]/g,initCheck:!1},initialize:function(a,b,c){this.setOptions(c);this.target=$(a);this.info=$(b);this.info.className=this.options.defClass;this.info.setStyle("visibility","visible");this.target.addEvent("keyup",this.check.bind(this));
this.options.initCheck&&this.reset();return this},check:function(){var a=!1,b=this.target.value.length,c=this.target.value.replace(this.options.invalidCharsRegExp,"").length;c<this.options.min?this.setInfo(this.options.minMsg,!0,this.options.min-c):b>this.options.max?this.setInfo(this.options.maxMag,!0,b-this.options.max):(a=!0,this.setInfo(this.options.msg,!1,this.options.max-b));return a},reset:function(){setTimeout(function(){this.check();return this}.bind(this),10)},setInfo:function(a,b,c){a=
a.replace("min",this.options.min).replace("max",this.options.max).replace("num",c);this.info.className=b?this.options.errorClass:this.options.defClass;this.info.set("html",a)}});
DP.Form.TagSelector=new Class({Implements:[Options],options:{lineClass:"tagdiv",titleClass:"tagtitle",listClass:"taglist",selectClass:"tagon",data:null,itemParentTag:"span",split:" ",allowEmpty:!1,hasTitle:!0},initialize:function(a,b,c){this.setOptions(c);this.holder=$(b);this.input=$(a);if(!this.holder||!this.input)return this.init=$empty,this;this.input.addEvent("keyup",function(){this.checkTagsForRemove()}.bind(this));this.inited=!1;this.options.data&&this.init(this.options.data);return this},
init:function(a){var b=this,c=b.__check=function(){var a=this.get("html").trim();b.changeTag(a,b.checkTag(a));return!1};if(a){this.clearTag();for(var d,e=this.prepareInputedTags(),g=0;g<a.length;g++)if(this.options.allowEmpty||a[g].tags.length){var f=(new Element("div")).addClass(this.options.lineClass).inject(this.holder);b.options.hasTitle&&(new Element("span")).set("html",a[g].name+":").addClass(this.options.titleClass).inject(f);var i;d=b.tagEle=(new Element(b.options.itemParentTag)).addClass(this.options.listClass).inject(f);
(i=a[g].tags)&&i.each(function(a){if(""!=a){var f=(new Element("a")).set("href","#").set("html",a).set("rel","nofollow").addEvent("click",c).inject(d),g=b.options.itemClass;g&&f.addClass(g);e.contains(a)&&f.addClass(b.options.selectClass)}})}}this.tagSpans=this.holder.getElements((this.options.listClass?"."+this.options.listClass+" ":"")+"a");a||this.tagSpans.length&&this.tagSpans.each(function(a){a.addEvent("click",c)});this.inited=!0;return this},_getTagTexts:function(){var a=[];this.tagSpans.forEach(function(b){a.push(b.get("text"))});
return a},addTag:function(a,b){var c=this,d=c.options.itemClass,e,g;if(a=a.trim()){e=c.prepareInputedTags(a);for(var f=[],i,j=e.length;j--;)i=e[j],-1===f.indexOf(i)&&f.push(i);e=f.reverse();e.forEach(function(a){-1===c._getTagTexts().indexOf(a)?(g=(new Element("a")).set("href","#").set("html",a).set("rel","nofollow").addEvent("click",c.__check),b?g.inject(b,"after"):g.inject(c.tagEle,"top"),c.tagSpans.push(g),d&&g.addClass(d),g.fireEvent("click")):c.changeTag(a,c.checkTag(a))});return g||b}return b},
prepareInputedTags:function(a){a=a||this.input.value;return""==a?[]:a.trim().replace(/\s+|　+/g," ").split(this.options.split).map(function(a){return a.trim()})},checkTagsForRemove:function(){if(this.inited){var a=this.prepareInputedTags();this.tagSpans.each(function(b){a.contains(b.get("html"))?b.addClass(this.options.selectClass):b.removeClass(this.options.selectClass)}.bind(this))}return this},changeTag:function(a,b){this.tagSpans.each(function(c){c.get("html").trim()==a&&(b?c.addClass(this.options.selectClass):
c.removeClass(this.options.selectClass))}.bind(this))},checkTag:function(a){var b=this.prepareInputedTags();if(b.contains(a))return this.input.value=b.erase(a).join(this.options.split),!1;this.input.value=this.input.value.trim()+(b.length?this.options.split:"")+a;return!0},clearTag:function(){this.holder.getChildren().destroy();return this}});if(!window.TagSelector)var TagSelector=DP.Form.TagSelector;
(function(a){var b=["&nbsp;","&gt;","&lt;",/<br\s*(\/)?>/ig,"&quot;","&amp;"],c=' ><\n"&'.split(""),d="&nbsp; &gt; &lt; <br/> &quot; &amp;".split(" "),e=function(a,b,d){for(var c=0,e=b.length;c<e;++c)a=a.replace("string"===$type(b[c])?RegExp(b[c],"ig"):b[c],d[c]);return a},a=a.Form;a.format=a.format||{};a.format={toHTML:function(a){return e(a,c,d)},toValue:function(a){return e(a,b,c)}}})(DP);


var Fvalid={};
Fvalid.Base=new Class({Implements:[Options,Events],options:{checkNoneClass:"fv-def",checkOkClass:"fv-ok",checkErrClass:"fv-err",bangClass:"fv-bang",useFx:!1,fxOptions:{},criterias:[],errMsg:[],msgHolder:!1,msg:null,vid:null,bangs:null,onChecked:$empty},initialize:function(a){this.setOptions(a);this.bangs=this.options.bangs;this.msgHolder=$(this.options.msgHolder);this.msg=this.options.msg;this.options.useFx?this.fx=new Fx.Tween(this.msgHolder,$merge({property:"opacity",duration:200},this.options.fxOptions)):
this.fx=null;this.msgHolder&&(this.fx?this.fx.set(0):this.msgHolder.setStyle("visibility","hidden"),this.msgHolder.className=this.options.checkNoneClass);this.msgHolder&&this.msgHolder.get("html")?(this.msgHolder.className=this.options.checkErrClass,this.fx?this.fx.set(1):this.msgHolder.setStyle("visibility","visible")):this.msgHolder&&this.msg&&(this.msgHolder.set("text",this.msg[0]),this.fx?this.fx.set(1):this.msgHolder.setStyle("visibility","visible"));this.options.vid&&null!=$(this.options.vid)&&
("select"==$(this.options.vid).tagName.toLowerCase()&&$(this.options.vid).addEvent("change",this.check.bind(this)),$(this.options.vid).addEvent("blur",this.check.bind(this)));this.buildCriteria();return this},buildCriteria:function(){return this},check:function(){for(var a=!0,b=0;b<this.options.criterias.length;b++)if(!eval(this.options.criterias[b]))return this.msgHolder&&this._setError(b),a=!1,this.bangs&&this.fireEvent("checked",[a,this.bangs[0]]),a;this.msgHolder&&this._setOk();this.bangs&&this.fireEvent("checked",
[a,this.bangs[0]]);return a},_setError:function(a){this.resetBangs();this.setMsg(this.options.errMsg[a],this.options.checkErrClass,this.msg?"msg":"open");this.bangs&&this.bangs.each(function(a){$(a).addClass(this.options.bangClass)}.bind(this));return this},_setOk:function(){this.resetBangs();this.setMsg(this.msg?this.msg[1]:"",this.options.checkOkClass,this.msg?"msg":"close");return this},setError:function(a,b){b=b||!0;this.resetBangs();this.setMsg(a,this.options.checkErrClass,this.msg?"msg":b?"open":
"close");this.bangs&&this.bangs.each(function(a){$(a).addClass(this.options.bangClass)}.bind(this));return this},setOk:function(a,b){b=b||!1;this.resetBangs();this.setMsg(a,this.options.checkOkClass,this.msg?"msg":b?"open":"close");return this},setMsg:function(a,b,c){this.msgHolder.className=b;this.msgHolder.set("text",a);switch(c){case "open":this.fx?this.fx.start(1):this.msgHolder.setStyle("visibility","visible");break;case "close":this.fx?this.fx.start(0):this.msgHolder.setStyle("visibility","hidden")}},
resetBangs:function(){this.bangs&&this.bangs.each(function(a){$(a).removeClass(this.options.bangClass)}.bind(this));return this},reset:function(){this.resetBangs();this.setMsg(this.msg?this.msg[0]:"",this.options.checkNoneClass,this.msg?"open":"close")}});
var Fvalidator=new Class({initialize:function(a){this.checkerSets={};this.bangAt=[];for(var b in a)switch(a[b].check.onChecked=this.addToBang.bind(this),a[b].type){case "textarea":this[b]=this.checkerSets[b]=new Fvalid.TextAreaCheck(a[b].check);break;case "advanced":this[b]=this.checkerSets[b]=new Fvalid.Advanced(a[b].check);break;default:this[b]=this.checkerSets[b]=new Fvalid.Base(a[b].check)}window.windowScroll||(windowScroll=new Fx.Scroll(window));return this},add:function(a){if("object"!=$type(a))return!1;
$H(a).each(function(a,c){a.addEvent("checked",this.addToBang.bind(this));this[c]=this.checkerSets[c]=a},this);return this},remove:function(a){if(!this[a])return!1;delete this[a];delete this.checkerSets[a];return this},checkAll:function(){this.bangAt=this.bangAt.empty();var a=!0,b;for(b in this.checkerSets)this.checkerSets[b].check()||(a=!1);(this.bangAt=this.bangAt.clean())&&this.bangAt.length&&windowScroll.toElement(this.bangAt[0]);return a},reset:function(){for(var a in this.checkerSets)this.checkerSets[a].reset()},
addToBang:function(a,b){a?this.bangAt.erase(b):this.bangAt.include(b)}});Fvalid.TextLengthLimit=new Class({Extends:Fvalid.Base,buildCriteria:function(){var a=this.options.opt||{};a.origClassName=this.origClassName;this.textLengthLimit=new DP.Form.LengthLimit(this.options.vid,this.options.msgHolder,a);return this},check:function(){var a=this.textLengthLimit.check();this.bangs&&this.fireEvent("checked",[a,this.bangs[0]]);return a},reset:function(){this.resetBangs();this.textLengthLimit.reset();return this}});


(function(g,s){function n(a,b){return"string"===g.type(a)?a.trim().split(b||","):g.makeArray(a)}function o(a,b){for(var c=0,d=a.length,e=0;c<d&&(!a[c].checked||!(++e,b));c++);return e}function p(a,b){return function(){return a.apply(b,arguments)}}function k(a,b){return"function"===g.type(a)?p(a,b):b[a]=p(b[a],b)}var t=/^(?:\.|#)/,u=/^(?:[a-z0-9!#$%&'*+\/=?^_`{|}~-]\.?){0,63}[a-z0-9!#$%&'*+\/=?^_`{|}~-]@(?:(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\])$/i,
j=g.Form,l,i,q={input:{"max-length":{test:function(a,b){return a.length<=b}},"min-length":{test:function(a,b){return a.length>=b}},required:{test:function(a){return!!a}},email:{test:function(a){return u.test(a)}},regex:{test:function(a,b){return("regexp"===g.type(b)?b:RegExp(b)).test(a)}}},checkbox:{required:{test:function(a){return o(a,!0)}}},radio:{required:{test:function(a){return o(a,!0)}}}};i=function(){var a=[];this.element.each(function(b){b.checked&&a.push(b.value)});return a.join(this.options.splitter||
"|")};var r=function(){return this.element},m={checkOnBlur:!0,showMsgOnBlur:!0,trim:!0,errCls:"err-input",errHideCls:"Hide",testRuleAttr:"data-validate-rule",errMsgAttr:"data-err-msg",_Val:{input:function(){var a=this.element.get("value");return this.options.trim?a.trim():a},checkbox:i,radio:i},_getCheckObj:{input:function(){return this.val()},checkbox:r,radio:r}},v={enableHTML5:!0,CSPrefix:"",errCSSuffix:"-err",showAllErr:!1};l=new Class({Implements:Options,initialize:function(a,b,c,d){a="string"===
g.type(a)?t.test(a)?$$(a):$(a):a;b=$(b);if(a){var e=this,f,h,w=g.type,i=c.type;e.setOptions(m,d);f=e.options;!i&&"element"===w(a)&&(i="input");e._config(i);e.element=a;e.errHolder=b;!c&&a?(b=a.getAttribute(f.testRuleAttr).replace(/\\\\/g,"\\"),h=a.getAttribute(f.errMsgAttr)):(b=c.test,h=c.errMsg);b=n(b||function(){return true});h=n(h||[]);b.each(function(a,b){e.addValidator(a,h[b])});f.checkOnBlur&&a.addEvent("blur",function(){e.check(f.showMsgOnBlur)});k("val",e);k("check",e);k("addValidator",e)}},
_config:function(a){var b=this.options;if(!a)throw new TypeError("Form.Validator: invalid validate type");this._type=a;this._getCheckObj=m._getCheckObj[a];this._val=b.getVal||m._Val[a];delete b.getVal},_errMsg:[],_tests:[],showMsg:function(a){var b=this.errHolder,c=this.options,a=a||"";b&&b[a?"removeClass":"addClass"](c.errHideCls).set("html",a)},val:function(a){return"function"===g.type(a)?(this._val=a,this):this._val.call(this)},check:function(a){for(var b=this,c=0,d=b._tests,e=d.length,f,h=!0,
g=b._getCheckObj();c<e&&!(f=d[c],!0===f.ajax?f(g,function(c,d){c||(h=!1,a&&b._fail(a,d,g))}):f(g)||(h=!1,a&&b._fail(a,b._errMsg[c],g)),!h);c++);h&&a&&b.showMsg();return h},_fail:function(a,b,c){this.element[a?"addClass":"removeClass"](this.options.errCls);(a||a===s)&&this.showMsg((b||"").substitute({value:c}))},addValidator:function(a,b){var c;switch(g.type(a)){case "string":a=a.split(":");(a[1]||"").trim();a=q[this._type][a[0].trim()];break;case "function":a={test:a}}if(a&&a.test&&(!a.condition||
a.condition(this.element))){c=function(){return a.test.apply(null,arguments)};if(a.ajax||a.test.ajax)c.ajax=!0;this._tests.push(c);this._errMsg.push(b)}}});i=new Class({_vals:{},_checks:[],_HTML5:function(a,b){a.getAttribute("placeholder")&&new j.Placeholder(a,{valSetter:b.val})},Implements:Options,initialize:function(a,b,c){var d,e,f,g;this.setOptions(v,c);d=this.options;if(a=$(a))for(e in b)f=b[e],g=f.CS||e,this.add(a.getElement(d.CSPrefix+g),a.getElement(d.CSPrefix+(f.errCS||g+d.errCSSuffix)),
e,f,c)},add:function(a,b,c,d,e){element=$(a);b=$(b);if(element){var f=this,a=!0;if("checkbox"===d.type||"radio"===d.type)element=element.getElements("input[type="+d.type+"]"),a=!1;b=new l(element,b,d,e);a&&f.options.enableHTML5&&f._HTML5(element,b);f._checks.push(b.check);f._vals[c]=b.val}return f},check:function(a){for(var a=a||void 0===a,b=this.options.showAllErr,c=0,d=!0,e=this._checks.length,f;c<e&&!(f=this._checks[c],d=f(a)&&d,!d&&!b);c++);return d},val:function(a){var b={},c,d=this._vals;for(c in d)b[c]=
d[c]();return a?g.toQueryString(b):b}});j.addValidator=function(a,b,c){q[c||"input"][a]=b};j.Validator=l;j.Complex=i})(DP);
