<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<div class="footer footer-static">
		<ul>
			<li><a target="_blank" href="" rel="nofollow">关于点评</a>|</li>
			<li><a target="_blank"
				href="http://s.dianping.com/topic/2815561" rel="nofollow">诚信公约</a>|</li>
			<li><a target="_blank" href="http://www.dianping.com/help"
				rel="nofollow">网站帮助</a>|</li>
			<li><a target="_blank" href="http://www.dianping.com/business/"
				rel="nofollow">推广服务</a>|</li>
			<li><a target="_blank"
				href="http://www.dianping.com/aboutus/media" rel="nofollow">媒体报道</a>|</li>
			<li><a target="_blank" href="http://careers.dianping.com"
				rel="nofollow">人才招聘</a>|</li>
			<li><a target="_blank" href="http://www.dianping.com/forum"
				rel="nofollow">站务论坛</a>|</li>
			<li><a target="_blank" href="http://www.dianping.com/contactus"
				rel="nofollow">联系我们</a>|</li>
			<li><a target="_blank" href="http://developer.dianping.com"
				rel="nofollow">开发者</a>|</li>
			<li class="fn-tuan"><a href="javascript:;"
				onclick="return false;">点评团</a></li>
		</ul>
		<p>
			&copy;20014-2014 dianping.com, All Rights Reserved.
			本站发布的所有内容，未经许可，不得转载，详见<a
				href="http://www.dianping.com/aboutus/zhishichanquan.html"
				rel="nofollow">《知识产权声明》</a>。
		</p>
	</div>